# Generated by Django 5.0.2 on 2024-06-11 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dateAndTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
